dist: bionic
language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq apache2-dev libglib2.0-dev liblasso3-dev libssl-dev
script: ./autogen.sh && ./configure CFLAGS=-Werror && make && make distfile
